### ISSUE TITLE
Query kubernetes_pod_containers table failed

### ISSUE THREAD

**Issue by keepwn** [Uptycs/kubequery#16]
**Describe the bug**
query `kubernetes_pod_containers` table failed, error is `Extension call failed: No more data to read`

**To Reproduce**
run `SELECT * FROM kubernetes_pod_containers;`

**Expected behavior**
k8s containers should be returned

**Screenshots**
```
panic: runtime error: index out of range [0] with length 0

goroutine 198 [running]:
github.com/Uptycs/kubequery/internal/k8s/core.PodContainersGenerate(0x1a4b7f0, 0xc000046048, 0xc000380960, 0x0, 0x0, 0x0, 0xc000089b10, 0x40fc38)
	/home/runner/work/kubequery/kubequery/internal/k8s/core/pod.go:133 +0xb05
github.com/Uptycs/basequery-go/plugin/table.(*Plugin).Call(0xc0001cf830, 0x1a4b7f0, 0xc000046048, 0xc000380270, 0xc00025f3b8, 0xc000688001, 0x0, 0xc000089b88)
	/home/runner/go/pkg/mod/github.com/!uptycs/basequery-go@v0.5.0/plugin/table/table.go:68 +0x366
github.com/Uptycs/basequery-go.(*ExtensionManagerServer).Call(0xc000160360, 0x1a4b7b8, 0xc002210240, 0xc003b3a061, 0x5, 0xc0010c6000, 0x19, 0xc000380270, 0x6ea9dc, 0xc0004684d0, ...)
	/home/runner/go/pkg/mod/github.com/!uptycs/basequery-go@v0.5.0/server.go:254 +0x10f
github.com/Uptycs/basequery-go/gen/osquery.(*extensionProcessorCall).Process(0xc00021de10, 0x1a4b7b8, 0xc002210240, 0x0, 0x1a67ca8, 0xc0004684d0, 0x1a67ca8, 0xc000468540, 0x176b600, 0x0, ...)
	/home/runner/go/pkg/mod/github.com/!uptycs/basequery-go@v0.5.0/gen/osquery/osquery.go:1449 +0x1c6
github.com/Uptycs/basequery-go/gen/osquery.(*ExtensionProcessor).Process(0xc00000e0c0, 0x1a4b860, 0xc0001cedb0, 0x1a67ca8, 0xc0004684d0, 0x1a67ca8, 0xc000468540, 0xc0001cedb0, 0x7f34383b7aa8, 0x419c37)
	/home/runner/go/pkg/mod/github.com/!uptycs/basequery-go@v0.5.0/gen/osquery/osquery.go:1311 +0x3b4
github.com/apache/thrift/lib/go/thrift.(*TSimpleServer).processRequests(0xc00014e140, 0x1a56b78, 0xc0001ce510, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/apache/thrift@v0.14.0/lib/go/thrift/simple_server.go:316 +0x31e
github.com/apache/thrift/lib/go/thrift.(*TSimpleServer).innerAccept.func1(0xc00014e140, 0x1a56b78, 0xc0001ce510)
	/home/runner/go/pkg/mod/github.com/apache/thrift@v0.14.0/lib/go/thrift/simple_server.go:198 +0x6f
created by github.com/apache/thrift/lib/go/thrift.(*TSimpleServer).innerAccept
	/home/runner/go/pkg/mod/github.com/apache/thrift@v0.14.0/lib/go/thrift/simple_server.go:196 +0x15f
W0723 07:13:11.395772    15 watcher.cpp:602] Extension respawning too quickly: /opt/uptycs/bin/kubequery.ext
I0723 07:13:11.396102    15 watcher.cpp:636] Created and monitoring extension child (19639): /opt/uptycs/bin/kubequery.ext
I0723 07:13:11.458142    49 extensions.cpp:348] Extension UUID 36288 has gone away
```

**Additional context**
kubelet_version: v1.18.8
kubeproxy_version: v1.18.8
container_runtime_version: docker://18.6.1

**Comment by spasam** [comment]
Thanks for the report @keepwn . This should be resolved now in latest image.
